(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const n=document.querySelector("#task-list");document.querySelector(".task-list-item");document.querySelector(".task-list-item-btn");const c=document.querySelector(".header-form");function l({Title:s,Description:e}){const o=`<li class="task-list-item">
          <button class="task-list-item-btn">Delete</button>
          <h3>${s}</h3>
          <p>${e}</p>
        </li>`;n.insertAdjacentHTML("beforeend",o)}function u(s){const e=JSON.parse(localStorage.getItem("keyTask"))||[];e.push(s),localStorage.setItem("keyTask",JSON.stringify(e))}function m(){const e=(JSON.parse(localStorage.getItem("keyTask"))||[]).map(({Title:o,Description:i})=>`<li class="task-list-item">
          <button class="task-list-item-btn">Delete</button>
          <h3>${o}</h3>
          <p>${i}</p>
        </li>`).join("");n.innerHTML=e}function f(s){const o=(JSON.parse(localStorage.getItem("keyTask"))||[]).filter((i,t)=>t!==s);localStorage.setItem("keyTask",JSON.stringify(o))}m();c.addEventListener("submit",s=>{s.preventDefault();const e=s.target.taskName.value.trim(),o=s.target.taskDescription.value.trim();(!e||!o)&&alert("Заповніть всі поля форми!");const i={Title:e,Description:o};l(i),u(i),console.log(e),console.log(o),c.reset()});console.log(n);n.addEventListener("click",s=>{if(s.target.classList.contains("task-list-item-btn")){const e=s.target.closest(".task-list-item"),o=[...n.children].indexOf(e);e.remove(),f(o)}});
//# sourceMappingURL=index.js.map
